apiVersion: v1
kind: Pod
metadata:
  name: webserver
  labels:
    app: employees
    component: app
spec:
 containers:
 - name: webserver
   image: 544714521291.dkr.ecr.us-east-1.amazonaws.com/psamin2-ecr:appv1.0
   env:
   - name: DBHOST
     value: mysql.myns.svc.cluster.local  # Replace with the hostname of your MySQL service
   - name: DBUSER
     value: root
   - name: DBPWD
     value: pw  # Replace with your MySQL password

   ports:
   - containerPort: 8080
