apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  labels:
    app: employees
    component: app
spec:
  selector:
    matchLabels:
      app: employees
      component: app
  replicas: 3
  template:
    metadata:
      labels:
        app: employees
        component: app
    spec:
      containers:
      - name: webserver
        image: 544714521291.dkr.ecr.us-east-1.amazonaws.com/psamin2-ecr:appv1.0
        env:
        - name: DBHOST
          value: mysql.appdbns.svc.cluster.local  # Replace with the hostname of your MySQL service
        - name: DBUSER
          value: root
        - name: DBPWD
          value: pw  # Replace with your MySQL password
        - name: DATABASE
          value: employees  # Replace with your MySQL database name
        
        ports:
        - containerPort: 8080
